FROM --platform=linux/x86_64 alpine:3.15
LABEL author="atif.libra.ali@gmail.com"



RUN apk update \
    && apk add nginx \
    supervisor \
    && adduser -D -u 1000 -g 'www' www  \
    && mkdir -p /run/nginx/
    # && chown -R www:www /var/lib/nginx \
    # && chown -R www:www /www \
    # && rm -rf /etc/nginx/nginx.conf

ENV PHP_FPM_USER="www"
ENV PHP_FPM_GROUP="www"
ENV PHP_FPM_LISTEN_MODE="0660"
ENV PHP_MEMORY_LIMIT="512M"
ENV PHP_MAX_UPLOAD="50M"
ENV PHP_MAX_FILE_UPLOAD="200"
ENV PHP_MAX_POST="100M"
ENV PHP_DISPLAY_ERRORS="On"
ENV PHP_DISPLAY_STARTUP_ERRORS="On"
ENV PHP_ERROR_REPORTING="E_COMPILE_ERROR\|E_RECOVERABLE_ERROR\|E_ERROR\|E_CORE_ERROR"
ENV PHP_CGI_FIX_PATHINFO=0
ENV TIMEZONE="UTC"

RUN apk add curl busybox-extras \
    ssmtp \
    tzdata \
    php7-fpm \
    php7-soap \
    php7-openssl \
    php7-gmp \
    php7-pdo_odbc \
    php7-json \
    php7-dom \
    php7-pdo \
    php7-zip \
    php7-mysqli \
    php7-sqlite3 \
    php7-pdo_pgsql \
    php7-bcmath \
    php7-gd \
    php7-odbc \
    php7-pdo_mysql \
    php7-pdo_sqlite \
    php7-gettext \
    php7-xmlreader \
    php7-bz2 \
    php7-iconv \
    php7-pdo_dblib \
    php7-curl \
    php7-ctype \
    php7-tokenizer\
    php7-phar \
    php7-fileinfo \
    php7-xml \
    php7-simplexml \
    php7-xmlwriter \
    php7-calendar \
    php7-dba \
    php7-enchant \
    php7-exif \
    php7-ftp \
    php7-pecl-imagick \
    php7-imap \
    php7-intl \
    php7-ldap \
    php7-mbstring \
    php7-pcntl \
    php7-pgsql \ 
    php7-posix \
    php7-pspell \
    php7-session \
    php7-shmop \
    php7-snmp \
    php7-redis \
    php7-sockets \
    php7-sodium \
    php7-sysvmsg \
    php7-sysvsem \
    php7-sysvshm \
    php7-xsl \
    php7-opcache
    

RUN sed -i "s|display_errors\s*=\s*Off|display_errors = ${PHP_DISPLAY_ERRORS}|i" /etc/php7/php.ini \
    && sed -i "s|display_startup_errors\s*=\s*Off|display_startup_errors = ${PHP_DISPLAY_STARTUP_ERRORS}|i" /etc/php7/php.ini \
    && sed -i "s|error_reporting\s*=\s*E_ALL & ~E_DEPRECATED & ~E_STRICT|error_reporting = ${PHP_ERROR_REPORTING}|i" /etc/php7/php.ini \
    && sed -i "s|;*memory_limit =.*|memory_limit = ${PHP_MEMORY_LIMIT}|i" /etc/php7/php.ini \
    && sed -i "s|;*upload_max_filesize =.*|upload_max_filesize = ${PHP_MAX_UPLOAD}|i" /etc/php7/php.ini \
    && sed -i "s|;*max_file_uploads =.*|max_file_uploads = ${PHP_MAX_FILE_UPLOAD}|i" /etc/php7/php.ini \
    && sed -i "s|;*post_max_size =.*|post_max_size = ${PHP_MAX_POST}|i" /etc/php7/php.ini \
    && sed -i "s|;*cgi.fix_pathinfo=.*|cgi.fix_pathinfo= ${PHP_CGI_FIX_PATHINFO}|i" /etc/php7/php.ini \
    && sed -i 's/smtp_port\ =\ 25/smtp_port\ =\ 81/g' /etc/php7/php.ini \
    && sed -i 's/SMTP\ =\ localhost/SMTP\ =\ mail.bekkersolutions.com/g' /etc/php7/php.ini \
    && sed -i 's/;sendmail_path\ =/sendmail_path\ =\ \/usr\/sbin\/sendmail\ -t/g' /etc/php7/php.ini

RUN rm -rf /etc/localtime \
    && ln -s /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && echo "${TIMEZONE}" > /etc/timezone \
    && sed -i "s|;*date.timezone =.*|date.timezone = ${TIMEZONE}|i" /etc/php7/php.ini \ 
    && echo 'sendmail_path = "/usr/sbin/ssmtp -t "' > /etc/php7/conf.d/mail.ini \
    && sed -i 's/mailhub=mail/mailhub=mail.domain.com\:81/g' /etc/ssmtp/ssmtp.conf

COPY .docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY php/www.conf /etc/php7/php-fpm.d/www.conf
COPY .docker/nginx/conf.d/000-default.conf /etc/nginx/conf.d/000-default.conf
RUN mkdir -p /etc/supervisor.d/
COPY .docker/supervisord.ini /etc/supervisor.d/supervisord.ini

# Configure PHP
# RUN mkdir -p /run/php/
# RUN touch /run/php/php8.0-fpm.pid

# RUN mkdir -p /run/nginx/
# RUN touch /run/nginx/nginx.pid

# RUN ln -sf /dev/stdout /var/log/nginx/access.log
# RUN ln -sf /dev/stderr /var/log/nginx/error.log

#Copy Services Scripts
COPY scripts/start_nginx.sh /usr/local/bin/start_nginx.sh
COPY scripts/start_php-fpm8.sh /usr/local/bin/start_php-fpm8.sh
COPY scripts/services_robe.sh /usr/local/bin/services_robe.sh

RUN chmod +x /usr/local/bin/start_nginx.sh /usr/local/bin/start_php-fpm8.sh /usr/local/bin/services_robe.sh

# if need composer to update plugin / vendor used
RUN php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php --install-dir=/usr/bin --filename=composer && \
php -r "unlink('composer-setup.php');"

WORKDIR /var/app/current
EXPOSE 9000
EXPOSE 80 443
CMD ["/usr/local/bin/services_robe.sh"]