version: "3.9"
# Services
services:
  # Nginx & PHP Service
  php7.4:
    platform: linux/x86_64
    # platform: linux/amd64
    build:
      context: .     
      dockerfile: ./Dockerfile-alpine
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    working_dir: /var/app/current
    volumes:
      - ./apps:/var/app/current
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: php7.4
    hostname: php7.4
    restart: always
    networks:
    - lemp-network 

  # MYSQL 5.7 Service
  mysql-5.7:
    # platform: linux/x86_64
    platform: linux/amd64
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - ./mysql-5.7:/var/lib/mysql
    - ./apps:/var/app/current
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
    - lemp-network  

networks:
  lemp-network:
    driver: bridge